Vagrant.configure("2") do |config|
  config.vm.hostname = "worker1"
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.provision "shell", path: "provision.sh"
end
